languageCode = "en-us"
Title = "Lloyd Ramey"
theme = "cocoa"
baseUrl = "https://lloydramey.com/"
enableRobotsTXT = true

[permalinks]
fixed = ":slug/"
home = ":slug"

[params]
DateForm = "Jan 2, 2006"
DateFormFull = "Mon Jan 2 2006 15:04:05 EST"
Lang = "en"
Twitter = "https://twitter.com/atrayan"
GitHub = "https://github.com/lnr0626"
GitLab = "https://gitlab.com/u/lnr0626"
LinkedIn = "https://www.linkedin.com/in/lloyd-ramey-97122a4a"
Email = "public@lloydramey.com"
Author = "Lloyd Ramey"
CodeBlogUrl = "https://anothermakersjourney.com/"
FoodBlogUrl = "https://derivativefood.com/"
GATracker = "UA-52697147-4"