languageCode = "en-us"
Title = "Lloyd Ramey"
theme = "cocoa"
baseUrl = "https://lloydramey.com/"

[permalinks]
fixed = ":slug/"
home = ":slug"

[params]
DateForm = "Jan 2, 2006"
DateFormFull = "Mon Jan 2 2006 15:04:05 EST"
Lang = "en"
Twitter = "https://twitter.com/atrayan"
GitHub = "https://github.com/lnr0626"
GitLab = "https://gitlab.com/u/lnr0626"
LinkedIn = "https://www.linkedin.com/in/lloyd-ramey-97122a4a"
Facebook = "https://www.facebook.com/lnr0626"
Email = "lnr0626@gmail.com"
Author = "Lloyd Ramey"
BlogUrl = "https://anothermakersjourney.com/"