name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@722adc63f1aa60a57ec37892e133b1d319cae598
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Hugo setup
        uses: peaceiris/actions-hugo@10f36c7c9133c2fe4dba9a431e838d7c71980b13
        with:
          extended: true
      - name: Build
        env:
          HUGO_ENV: production
        run: hugo --gc --minify

      - name: Upload build artifact
        uses: actions/upload-artifact@3446296876d12d4e3a0f3145a3c87e67bf0a16b5
        with:
          name: resources
          path: public/

      - name: Upload to s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 sync --delete ./public/ s3://lloydramey.com/
